name: 🐛 Bug Report
description: Signaler un bug dans Claude Code Auto-Config
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de remplir ce bug report !

        **Avant de continuer**, vérifiez que :
        - [ ] Ce bug n'a pas déjà été reporté dans les [Issues](../../issues)
        - [ ] Vous avez reproduit le bug sur un projet test propre
        - [ ] C'est un bug de l'auto-config (pas de Claude Code lui-même)

  - type: dropdown
    id: version
    attributes:
      label: Version Auto-Config
      description: Quelle version utilisez-vous ?
      options:
        - v1.0.0
        - main branch (latest)
        - autre (précisez dans description)
    validations:
      required: true

  - type: input
    id: claude-version
    attributes:
      label: Version Claude Code
      description: "Exécutez: `claude --version`"
      placeholder: "ex: 2.0.74"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Système d'exploitation
      options:
        - macOS
        - Ubuntu / Linux
        - Windows
        - autre (précisez dans description)
    validations:
      required: true

  - type: dropdown
    id: project-type
    attributes:
      label: Type de projet
      description: Quel type de projet était détecté/forcé ?
      options:
        - frontend-react
        - frontend-vue
        - frontend-angular
        - frontend-svelte
        - fullstack-nextjs
        - fullstack-nuxt
        - backend-node
        - backend-nestjs
        - backend-fastapi
        - backend-django
        - backend-flask
        - devops-terraform
        - devops-docker
        - monorepo-turborepo
        - monorepo-nx
        - autre (précisez dans description)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Expliquez clairement le comportement observé vs le comportement attendu
      placeholder: |
        **Comportement attendu:**
        La config devrait générer un CLAUDE.md avec...

        **Comportement observé:**
        À la place, j'obtiens...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Étapes pour reproduire
      description: Comment reproduire ce bug ?
      placeholder: |
        1. Créer projet Next.js vierge: `npx create-next-app@latest`
        2. Lancer Claude Code: `claude`
        3. Exécuter: `/project:auto-config`
        4. Observer l'erreur...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Messages d'erreur
      description: Collez les erreurs, warnings, ou logs pertinents
      render: shell
      placeholder: |
        [Coller les logs ici]

  - type: textarea
    id: config
    attributes:
      label: Configuration générée (si pertinent)
      description: Collez le contenu de CLAUDE.md ou settings.json généré
      render: markdown
      placeholder: |
        ```json
        {
          "permissions": {
            // ...
          }
        }
        ```

  - type: textarea
    id: context
    attributes:
      label: Contexte additionnel
      description: Informations additionnelles (structure projet, package.json, etc.)
      placeholder: |
        Structure du projet:
        ```
        my-project/
        ├── src/
        ├── package.json
        └── ...
        ```

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist de vérification
      description: Confirmez que vous avez vérifié ces points
      options:
        - label: J'ai cherché dans les issues existantes
          required: true
        - label: J'ai testé avec la dernière version de l'auto-config
          required: true
        - label: J'ai reproduit le bug sur un projet propre
          required: true
        - label: C'est bien un bug de l'auto-config (pas de Claude Code)
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        **Merci pour votre contribution !** 🙏

        Une fois soumis, l'équipe triera l'issue et répondra dès que possible.
